Add sponsor logos
rubyunconfeu/2024-website pull request #5
Opened 2024-04-24 16:24 UTC by skorbut

Add all confirmed sponsors to website and add dedicated sponsor page.

2024-04-25 12:00 UTC, stefan-evernest requested changes

2024-04-25 12:00 UTC, stefan-evernest commented on index.html
> +    <section id="sponsor-gold" class="index-sponsors">
proposal: I'd put the first sponso section under the about section to not confuse visitors with that gigantic logo

2024-04-25 12:00 UTC, stefan-evernest commented on style.css
> +  width: 375px;
issue: this produces a horizontal scrollbar on iPhone SE due to limited screen size. Make sure to always have a `max-width` in place (as in gold sponsors)

2024-04-25 12:01 UTC, stefan-evernest commented on sponsors.html
issue: there should be a back button and / or a logo on header with link to the index file to make navigation easier

2024-04-29 07:10 UTC, emrox approved these changes

2024-04-29 07:10 UTC, emrox commented on style.css
> +  width: 375px;
https://github.com/rubyunconfeu/2024-website/pull/5/commits/f27166ae25ffd341a9dce39200dfceab1683eb7b

2024-04-29 07:12 UTC, merged